version: '3'
services:
  
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    hostname: "mariadb"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb-local:/bitnami/mariadb'
  
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis-local:/data'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

volumes:
  mariadb-local:
    driver: local
  redis-local:
    driver: local
